"""Reproducibly generate standalone MT5 EA, without modifying the MT4 source.
Run: python tools/build_mt5.py [--check]
"""
from pathlib import Path
import re
import sys
ROOT = Path(__file__).resolve().parents[1]


def render():
    source = (ROOT / 'gold_x9_FIXED.mq4').read_text()
    bridge = (ROOT / 'mt5/MT5Bridge.mqh').read_text()
    names = set(re.findall(r'\bX9((?:Order\w*|Orders\w*|Account\w*|MarketInfo|IsTesting|IsVisualMode|RefreshRates|GetLastError|ResetLastError))\(', bridge))
    for name in sorted(names, key=len, reverse=True):
        source = re.sub(r'\b' + name + r'\s*\(', 'X9' + name + '(', source)
    # MT5 already defines MODE_SPREAD (ENUM_SERIESMODE). Namespace every legacy mode.
    source = re.sub(r'\bMODE_[A-Z_]+\b', lambda m: 'X9_' + m.group(), source)
    source = source.replace('gold_x9_FIXED.mq4', 'gold_x9_MT5.mq5')
    source = source.replace('#property version     "6.750"', '#property version     "7.001"')
    source = source.replace('MQL4 port of', 'MT5 hedging port of')
    source = source.replace('gold_x9 v6.75 (MQL4)', 'gold_x9 MT5 v7.001 (HEDGING)')
    # MT5 order/position/deal identifiers must never be narrowed to 32 bits.
    source = re.sub(r'\bint(\s+)(ticket|lastTradeTicket|selTicket|selMagic|tickets|pendingTickets)\b', r'long\1\2', source)
    source = source.replace('int SendPendingOrder(', 'long SendPendingOrder(')
    source = source.replace('int    SendPendingOrder(', 'long   SendPendingOrder(')
    # The old write-only double ticket map is unnecessary and loses 64-bit precision.
    source = re.sub(r'^double\s+orderPriceMap\[100\]\[2\];\n', '', source, flags=re.M)
    source = re.sub(r'   for\(resetOuterIndex = 0;.*?orderPriceMap\[resetOuterIndex\]\[resetInnerIndex\] = 0\.0;\n', '', source, flags=re.S)
    source = re.sub(r'      for\(int m = 0; m < 100; m\+\+\)\n        \{.*?\n        \}\n', '', source, count=1, flags=re.S)
    # Polling failure must not turn an incomplete history into an empty curve/stats.
    source = source.replace('int total=X9OrdersHistoryTotal();', 'int total=X9OrdersHistoryTotal();\n   if(total<0) return;')
    source = source.replace('int OnInit()\n  {', '''int OnInit()
  {
   x9Magic=inputMagicNumber;
   if(AccountInfoInteger(ACCOUNT_MARGIN_MODE)!=ACCOUNT_MARGIN_MODE_RETAIL_HEDGING)
     { Print("X9 MT5 requires a HEDGING account; netting/exchange accounts are unsupported."); return INIT_FAILED; }
   if(!X9IsTesting() && AccountInfoInteger(ACCOUNT_TRADE_MODE)==ACCOUNT_TRADE_MODE_REAL && !mt5AllowLiveTrading)
     { Print("X9 MT5: live trading locked. Validate tester/demo first; mt5AllowLiveTrading is explicit opt-in."); return INIT_FAILED; }
   if(!X9BuildHistory()) { Print("X9 MT5: history unavailable; reattach after terminal synchronization.");return INIT_FAILED; }
''')
    # Keep stats intact if the broker history snapshot temporarily fails.
    source = source.replace('void RefreshStats()\n  {',
                            'void RefreshStats()\n  {\n   if(!X9BuildHistory()) return;')
    source = source.replace('   int      resetOuterIndex;\n', '').replace('   int      resetInnerIndex;\n', '')
    # MT5 ENUM_TIMEFRAMES H1 is 16385, not the MT4 minute value 60.
    source = re.sub(r'" M"\s*\+\s*IntegerToString\(Period\(\)\)', '" "+X9TimeframeLabel()', source)
    source = re.sub(r'" \| M"\s*\+\s*IntegerToString\(Period\(\)\)', '" | "+X9TimeframeLabel()', source)
    source += '\nstring X9TimeframeLabel(){return StringSubstr(EnumToString((ENUM_TIMEFRAMES)Period()),7); }\n'
    # History transactions invalidate snapshots; rendering never submits trades.
    source += '''
// MT5 events invalidate the deal cache; next normal tick/timer rebuilds it.
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,const MqlTradeResult &result)
  {
   x9HistoryDirty=true;
  }
'''
    marker = '#include <Canvas\\Canvas.mqh>'
    assert marker in source
    source = source.replace(marker, marker + '\n\n// BEGIN native MT5 adapter (generated inline)\n' + bridge + '\n// END native MT5 adapter\n', 1)
    return '// Generated by tools/build_mt5.py. Native MT5 hedging EA; see MT5_PORT.md.\n' + source


if __name__ == '__main__':
    output = ROOT / 'gold_x9_MT5.mq5'
    text = render()
    if '--check' in sys.argv:
        if not output.exists() or output.read_text() != text:
            raise SystemExit('MT5 output is stale: run python tools/build_mt5.py')
        print('MT5 generated source is current')
    else:
        output.write_bytes(text.replace('\n', '\r\n').encode())
        print(output)
